org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true

android.buildFeatures.buildConfig=true
android.nonFinalResIds=true
android.builtInKotlin=false
android.newDsl=false
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true